server:
  port: 8090

spring:
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    #properties:
      #dialect: org.hibernate.dialect.SQLServer2012Dialect


  datasource:
    #driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #url: jdbc:sqlserver://LAPTOP-ET2K0EOM\SQLEXPRESS\SQLEXPRESS:1433;databaseName=HorarioUniDB
    #username: SqlJava
    #password: 123456
    #driver-class-name: net.sourceforge.jtds.jdbc.Driver
    url: jdbc:sqlserver://dmucentral.database.windows.net:1433;database=generadorHorario;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: ucentral
    password: Practica5
    initialization-mode: always 
    